# Generated by Django 2.1.7 on 2019-03-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaudits', '0002_auto_20190307_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mongosubmit',
            name='_result',
        ),
        migrations.RemoveField(
            model_name='mongosubmit',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='mongosubmit',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='Status'),
        ),
    ]
