# Generated by Django 2.1.7 on 2019-03-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaudits', '0004_mongosubmit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mongosubmit',
            name='user',
        ),
        migrations.AddField(
            model_name='mongosubmit',
            name='created_by',
            field=models.CharField(default='', max_length=30, verbose_name='Created by'),
        ),
    ]
