# Generated by Django 2.1.7 on 2019-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaudits', '0005_auto_20190311_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='mongosubmit',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='title'),
        ),
    ]
